# Generated by Django 4.2.30 on 2026-05-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['project_id'],
            },
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwg_id', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='marking.project')),
            ],
            options={
                'ordering': ['project__project_id', 'dwg_id'],
            },
        ),
        migrations.CreateModel(
            name='WireEndpoint',
            fields=[
                ('endpoint_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('ref_id', models.CharField(max_length=64)),
                ('mark', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=64)),
                ('wire_type', models.CharField(blank=True, max_length=64)),
                ('wire_color', models.CharField(blank=True, max_length=32)),
                ('sync_status', models.CharField(choices=[('NEW', 'New'), ('SYNCED', 'Synced'), ('DIRTY', 'Dirty'), ('ERROR', 'Error')], default='NEW', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wire_endpoints', to='marking.drawing')),
            ],
            options={
                'ordering': ['drawing__project__project_id', 'drawing__dwg_id', 'ref_id', 'mark'],
                'indexes': [models.Index(fields=['ref_id'], name='marking_wir_ref_id_df445c_idx'), models.Index(fields=['sync_status'], name='marking_wir_sync_st_03b153_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='drawing',
            constraint=models.UniqueConstraint(fields=('project', 'dwg_id'), name='unique_drawing_per_project'),
        ),
    ]
