# Generated by Django 4.2.30 on 2026-05-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order_number',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
