# Generated by Django 4.2.30 on 2026-05-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0003_alter_project_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wireendpoint',
            name='endpoint_id',
            field=models.CharField(blank=True, max_length=32, primary_key=True, serialize=False),
        ),
    ]
