# Generated by Django 4.2.30 on 2026-05-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0004_alter_wireendpoint_endpoint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wireendpoint',
            name='mark',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='wireendpoint',
            name='position',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='wireendpoint',
            name='ref_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
