# Generated by Django 4.2.30 on 2026-05-25 08:39

import uuid

from django.db import migrations, models


def normalize_wireendpoint_ids(apps, schema_editor):
    WireEndpoint = apps.get_model("marking", "WireEndpoint")
    ref_id_map = {}

    for endpoint in WireEndpoint.objects.order_by():
        old_endpoint_id = endpoint.endpoint_id
        updates = {}

        try:
            uuid.UUID(str(endpoint.endpoint_id))
        except (TypeError, ValueError):
            updates["endpoint_id"] = str(uuid.uuid4())

        if endpoint.ref_id:
            try:
                uuid.UUID(str(endpoint.ref_id))
            except (TypeError, ValueError):
                if endpoint.ref_id not in ref_id_map:
                    ref_id_map[endpoint.ref_id] = str(uuid.uuid4())
                updates["ref_id"] = ref_id_map[endpoint.ref_id]

        if not endpoint.mark_1:
            updates["mark_1"] = "-"
        if not endpoint.mark_2:
            updates["mark_2"] = "-"
        if not endpoint.wire_type:
            updates["wire_type"] = "-"
        if not endpoint.wire_color:
            updates["wire_color"] = "-"

        if updates:
            WireEndpoint.objects.filter(endpoint_id=old_endpoint_id).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0005_alter_wireendpoint_mark_alter_wireendpoint_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wireendpoint',
            old_name='mark',
            new_name='mark_1',
        ),
        migrations.AddField(
            model_name='wireendpoint',
            name='mark_2',
            field=models.CharField(blank=True, default='-', max_length=128),
        ),
        migrations.AlterField(
            model_name='wireendpoint',
            name='endpoint_id',
            field=models.CharField(blank=True, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wireendpoint',
            name='ref_id',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='wireendpoint',
            name='wire_color',
            field=models.CharField(blank=True, default='-', max_length=32),
        ),
        migrations.AlterField(
            model_name='wireendpoint',
            name='wire_type',
            field=models.CharField(blank=True, default='-', max_length=64),
        ),
        migrations.RunPython(normalize_wireendpoint_ids, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='wireendpoint',
            options={'ordering': ['drawing__project__project_id', 'drawing__dwg_id', 'mark_1', 'ref_id']},
        ),
    ]
