# Generated by Django 4.2.30 on 2026-05-25 08:48

from django.db import migrations, models
import django.db.models.deletion


def migrate_wire_dictionaries(apps, schema_editor):
    WireEndpoint = apps.get_model("marking", "WireEndpoint")
    WireType = apps.get_model("marking", "WireType")
    WireColor = apps.get_model("marking", "WireColor")

    for endpoint in WireEndpoint.objects.order_by():
        wire_type_name = endpoint.wire_type_text or "-"
        wire_color_name = endpoint.wire_color_text or "-"
        wire_type, _ = WireType.objects.get_or_create(name=wire_type_name)
        wire_color, _ = WireColor.objects.get_or_create(name=wire_color_name)
        WireEndpoint.objects.filter(endpoint_id=endpoint.endpoint_id).update(
            wire_type=wire_type,
            wire_color=wire_color,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0006_alter_wireendpoint_options_remove_wireendpoint_mark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WireColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WireType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='wireendpoint',
            name='mark_1',
            field=models.CharField(blank=True, default='-', max_length=128),
        ),
        migrations.RenameField(
            model_name='wireendpoint',
            old_name='wire_color',
            new_name='wire_color_text',
        ),
        migrations.RenameField(
            model_name='wireendpoint',
            old_name='wire_type',
            new_name='wire_type_text',
        ),
        migrations.AddField(
            model_name='wireendpoint',
            name='wire_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wire_endpoints', to='marking.wirecolor'),
        ),
        migrations.AddField(
            model_name='wireendpoint',
            name='wire_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wire_endpoints', to='marking.wiretype'),
        ),
        migrations.RunPython(migrate_wire_dictionaries, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='wireendpoint',
            name='wire_color_text',
        ),
        migrations.RemoveField(
            model_name='wireendpoint',
            name='wire_type_text',
        ),
    ]
