# Generated by Django 4.2.30 on 2026-05-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0010_rename_business_id_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wireendpoint',
            name='marking_wir_ref_id_df445c_idx',
        ),
        migrations.AddIndex(
            model_name='wireendpoint',
            index=models.Index(fields=['ref'], name='marking_wir_ref_2d46b9_idx'),
        ),
    ]
