# Generated by Django 4.2.30 on 2026-05-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0015_remove_project_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinet',
            options={'ordering': ['project__project_code', 'code'], 'verbose_name': 'Шкаф', 'verbose_name_plural': 'Шкафы'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['project_code'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='wirecolor',
            options={'ordering': ['name'], 'verbose_name': 'Цвет провода', 'verbose_name_plural': 'Цвета проводов'},
        ),
        migrations.AlterModelOptions(
            name='wireendpoint',
            options={'ordering': ['cabinet__project__project_code', 'cabinet__code', 'mark_1', 'ref'], 'verbose_name': 'Маркировка', 'verbose_name_plural': 'Маркировка'},
        ),
        migrations.AlterModelOptions(
            name='wiretype',
            options={'ordering': ['name'], 'verbose_name': 'Тип провода', 'verbose_name_plural': 'Типы проводов'},
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='code',
            field=models.CharField(blank=True, max_length=36, verbose_name='UUID шкафа'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание шкафа'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название шкафа'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='marking.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, max_length=36, verbose_name='UUID проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(max_length=128, unique=True, verbose_name='Шифр проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='wirecolor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='wirecolor',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='wirecolor',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Цвет провода'),
        ),
        migrations.AlterField(
            model_name='wirecolor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='wireendpoint',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wire_endpoints', to='marking.cabinet', verbose_name='Шкаф'),
        ),
        migrations.AlterField(
            model_name='wireendpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='wireendpoint',
            name='mark_1',
            field=models.CharField(blank=True, default='-', max_length=128, verbose_name='Маркировка 1'),
        ),
        migrations.AlterField(
            model_name='wireendpoint',
            name='mark_2',
            field=models.CharField(blank=True, default='-', max_length=128, verbose_name='Маркировка 2'),
        ),
        migrations.AlterField(
            model_name='wireendpoint',
            name='ref',
            field=models.CharField(blank=True, max_length=36, verbose_name='UUID связи'),
        ),
        migrations.AlterField(
            model_name='wireendpoint',
            name='sync_status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('SYNCED', 'Синхронизирован'), ('DIRTY', 'Изменен'), ('ERROR', 'Ошибка')], default='NEW', max_length=16, verbose_name='Статус синхронизации'),
        ),
        migrations.AlterField(
            model_name='wireendpoint',
            name='uid',
            field=models.CharField(blank=True, max_length=36, primary_key=True, serialize=False, verbose_name='UUID маркировки'),
        ),
        migrations.AlterField(
            model_name='wireendpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='wireendpoint',
            name='wire_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wire_endpoints', to='marking.wirecolor', verbose_name='Цвет провода'),
        ),
        migrations.AlterField(
            model_name='wireendpoint',
            name='wire_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wire_endpoints', to='marking.wiretype', verbose_name='Тип провода'),
        ),
        migrations.AlterField(
            model_name='wiretype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='wiretype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='wiretype',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Тип провода'),
        ),
        migrations.AlterField(
            model_name='wiretype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
